apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: ports
  ports:
  - name: posts
    protocol: TCP
    port: 4000 # the port that the NodePort service will expose to outside
    targetPort: 4000 # the prt in container/pod
